### ISSUE TITLE
【推广】LyTeX 绿色套装

### ISSUE THREAD

**Issue by lon91ong** [mosesnow/LZUthesis#1]
原作地址：[Google Code](https://code.google.com/archive/p/lytex/) 

原作发布在：[LyTeX绿色套装](http://bbs.ctex.org/forum.php?mod=viewthread&tid=46857)

自己在维护的更新版本：https://github.com/lon91ong/LyTex-Portable

目前（2020-10-02）更新至最新版：LyX-2.3.5.2，MikTex-2.9.7442，TeXWorks-0.6.5

**Comment by vidon** [comment]
百度盘上还是6月份的安装包？

**Comment by lon91ong** [comment]
> 百度盘上还是6月份的安装包？

更新部分很小, 没有重新打包
