### ISSUE TITLE
Texlive 2021 编译之后小标题的问题, 如图

### ISSUE THREAD

**Issue by iamliukaifang** [mosesnow/LZUthesis#2]
<img width="633" alt="Screenshot 2021-05-25 at 13 23 31" src="https://user-images.githubusercontent.com/25928056/119490336-05180300-bd5d-11eb-986a-8f2a2ea9c618.png">

**Comment by mosesnow** [comment]
请测试最新版，已验证在Texlive 2020 下结果正常，[此处下载](https://github.com/mosesnow/LZUthesis/zipball/master)。

**Comment by iamliukaifang** [comment]
非常感谢, texlive 2021下编译仍然可以.
