### ISSUE TITLE
修改建议: 首页文字对齐?

### ISSUE THREAD

**Issue by iamliukaifang** [mosesnow/LZUthesis#3]
如下图, 如果文字左右两边分别对齐可能会更好看一些?
<img width="638" alt="Screenshot 2021-05-26 at 12 23 06" src="https://user-images.githubusercontent.com/25928056/119644968-d0b84b80-be1d-11eb-95bf-e5f76e711742.png">

**Comment by mosesnow** [comment]
[新版](https://github.com/mosesnow/LZUthesis/zipball/master)已对齐。

**Comment by mosesnow** [comment]
- 这个未对齐现象是在[commit 54f9aac](https://github.com/mosesnow/LZUthesis/commit/54f9aacc4235a002c3fe9509c01d20c9a0f1119e)设置Times字体后引入的问题，可能是字体设置导致了空格大小的变化；
- [commit 9be1011](https://github.com/mosesnow/LZUthesis/commit/9be1011bed5236da46cbc8be1aea7c1c065c3774)通过\makebox的方式对齐，实际是对齐的(通过选择文字可注意到)，但视觉上括号偏左；
- 在commit b1ed7c8中修复为在视觉上与[commit 54f9aac](https://github.com/mosesnow/LZUthesis/commit/54f9aacc4235a002c3fe9509c01d20c9a0f1119e)之前版本一致。

**Comment by iamliukaifang** [comment]
谢谢更新～祝好。
